#!/bin/bash -x

find input/results -name '*.json' -size 0c -exec rm {} \;
find input/results -name '*.json' -size 2c -exec rm {} \;
fdupes -N -d -1 input/results

bundle exec ruby report.rb input/results children/children_storage=Children::ChildrenStorage children/children_processor=Children::ChildrenProcessor,lib/processors/by_question_mapper_processor=ByQuestionMapperProcessor children/common_children_reporter=Children::CommonChildrenReporter > output/children.html
bundle exec ruby report.rb input/results children/children_storage=Children::ChildrenStorage children/children_processor=Children::ChildrenProcessor,lib/processors/analysis_prepare_processor=AnalysisPrepareProcessor children/table_children_reporter=Children::TableChildrenReporter > output/children.csv
bundle exec ruby report.rb input/results children/children_storage=Children::ChildrenStorage children/children_processor=Children::ChildrenProcessor,children/generations/generations_children_mapper_processor=Children::Generations::GenerationsChildrenMapperProcessor children/generations/generations_children_reporter=Children::Generations::GenerationsChildrenReporter > output/children_generations.html
bundle exec ruby report.rb input/results children/children_storage=Children::ChildrenStorage children/children_processor=Children::ChildrenProcessor,children/regions/regions_children_mapper_processor=Children::Regions::RegionsChildrenMapperProcessor children/regions/regions_children_reporter=Children::Regions::RegionsChildrenReporter > output/children_regions.html
bundle exec ruby report.rb input/results children/children_storage=Children::ChildrenStorage children/children_processor=Children::ChildrenProcessor,children/populations/populations_children_mapper_processor=Children::Populations::PopulationsChildrenMapperProcessor children/populations/populations_children_reporter=Children::Populations::PopulationsChildrenReporter > output/children_populations.html

bundle exec ruby report.rb input/results teachers/teachers_storage=Teachers::TeachersStorage teachers/teachers_processor=Teachers::TeachersProcessor,lib/processors/by_question_mapper_processor=ByQuestionMapperProcessor teachers/common_teachers_reporter=Teachers::CommonTeachersReporter > output/teachers.html
bundle exec ruby report.rb input/results teachers/teachers_storage=Teachers::TeachersStorage teachers/teachers_processor=Teachers::TeachersProcessor,lib/processors/analysis_prepare_processor=AnalysisPrepareProcessor teachers/table_teachers_reporter=Teachers::TableTeachersReporter > output/teachers.csv
bundle exec ruby report.rb input/results teachers/teachers_storage=Teachers::TeachersStorage teachers/teachers_processor=Teachers::TeachersProcessor,teachers/generations/generations_teachers_mapper_processor=Teachers::Generations::GenerationsTeachersMapperProcessor teachers/generations/generations_teachers_reporter=Teachers::Generations::GenerationsTeachersReporter > output/teachers_generations.html
bundle exec ruby report.rb input/results teachers/teachers_storage=Teachers::TeachersStorage teachers/teachers_processor=Teachers::TeachersProcessor,teachers/regions/regions_teachers_mapper_processor=Teachers::Regions::RegionsTeachersMapperProcessor teachers/regions/regions_teachers_reporter=Teachers::Regions::RegionsTeachersReporter > output/teachers_regions.html
bundle exec ruby report.rb input/results teachers/teachers_storage=Teachers::TeachersStorage teachers/teachers_processor=Teachers::TeachersProcessor,teachers/populations/populations_teachers_mapper_processor=Teachers::Populations::PopulationsTeachersMapperProcessor teachers/populations/populations_teachers_reporter=Teachers::Populations::PopulationsTeachersReporter > output/teachers_populations.html

bundle exec ruby report.rb input/results parents/parents_storage=Parents::ParentsStorage parents/parents_processor=Parents::ParentsProcessor,lib/processors/by_question_mapper_processor=ByQuestionMapperProcessor parents/common_parents_reporter=Parents::CommonParentsReporter > output/parents.html
bundle exec ruby report.rb input/results parents/parents_storage=Parents::ParentsStorage parents/parents_processor=Parents::ParentsProcessor,lib/processors/analysis_prepare_processor=AnalysisPrepareProcessor parents/table_parents_reporter=Parents::TableParentsReporter > output/parents.csv
bundle exec ruby report.rb input/results parents/parents_storage=Parents::ParentsStorage parents/parents_processor=Parents::ParentsProcessor,parents/generations/generations_parents_mapper_processor=Parents::Generations::GenerationsParentsMapperProcessor parents/generations/generations_parents_reporter=Parents::Generations::GenerationsParentsReporter > output/parents_generations.html
bundle exec ruby report.rb input/results parents/parents_storage=Parents::ParentsStorage parents/parents_processor=Parents::ParentsProcessor,parents/regions/regions_parents_mapper_processor=Parents::Regions::RegionsParentsMapperProcessor parents/regions/regions_parents_reporter=Parents::Regions::RegionsParentsReporter > output/parents_regions.html
bundle exec ruby report.rb input/results parents/parents_storage=Parents::ParentsStorage parents/parents_processor=Parents::ParentsProcessor,parents/populations/populations_parents_mapper_processor=Parents::Populations::PopulationsParentsMapperProcessor parents/populations/populations_parents_reporter=Parents::Populations::PopulationsParentsReporter > output/parents_populations.html

bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,lib/processors/by_question_mapper_processor=ByQuestionMapperProcessor comparings/common_comparing_reporter=Comparings::CommonComparingReporter > output/comparing.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,lib/processors/analysis_prepare_processor=AnalysisPrepareProcessor comparings/table_comparing_reporter=Comparings::TableComparingReporter > output/comparing.csv
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,comparings/professions/professions_comparing_mapper_processor=Comparings::Professions::ProfessionsComparingMapperProcessor comparings/professions/professions_comparing_reporter=Comparings::Professions::ProfessionsComparingReporter > output/comparing_professions.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,comparings/generations/generations_comparing_mapper_processor=Comparings::Generations::GenerationsComparingMapperProcessor comparings/generations/generations_comparing_reporter=Comparings::Generations::GenerationsComparingReporter > output/comparing_generations.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,comparings/regions/regions_comparing_mapper_processor=Comparings::Regions::RegionsComparingMapperProcessor comparings/regions/regions_comparing_reporter=Comparings::Regions::RegionsComparingReporter > output/comparing_regions.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,comparings/populations/populations_comparing_mapper_processor=Comparings::Populations::PopulationsComparingMapperProcessor comparings/populations/populations_comparing_reporter=Comparings::Populations::PopulationsComparingReporter > output/comparing_populations.html

bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,x/comparing_x_processor=X::ComparingXProcessor,lib/processors/by_question_mapper_processor=ByQuestionMapperProcessor x/common_comparing_x_reporter=X::CommonComparingXReporter > output/comparing_x.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,x/comparing_x_processor=X::ComparingXProcessor,comparings/populations/populations_comparing_mapper_processor=Comparings::Populations::PopulationsComparingMapperProcessor x/populations/populations_comparing_x_reporter=X::Populations::PopulationsComparingXReporter > output/comparing_x_populations.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,x/comparing_x_processor=X::ComparingXProcessor,comparings/regions/regions_comparing_mapper_processor=Comparings::Regions::RegionsComparingMapperProcessor x/regions/regions_comparing_x_reporter=X::Regions::RegionsComparingXReporter > output/comparing_x_regions.html

bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,y/comparing_y_processor=Y::ComparingYProcessor,lib/processors/by_question_mapper_processor=ByQuestionMapperProcessor y/common_comparing_y_reporter=Y::CommonComparingYReporter > output/comparing_y.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,y/comparing_y_processor=Y::ComparingYProcessor,comparings/populations/populations_comparing_mapper_processor=Comparings::Populations::PopulationsComparingMapperProcessor y/populations/populations_comparing_y_reporter=Y::Populations::PopulationsComparingYReporter > output/comparing_y_populations.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,y/comparing_y_processor=Y::ComparingYProcessor,comparings/regions/regions_comparing_mapper_processor=Comparings::Regions::RegionsComparingMapperProcessor y/regions/regions_comparing_y_reporter=Y::Regions::RegionsComparingYReporter > output/comparing_y_regions.html

bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,z/comparing_z_processor=Z::ComparingZProcessor,lib/processors/by_question_mapper_processor=ByQuestionMapperProcessor z/common_comparing_z_reporter=Z::CommonComparingZReporter > output/comparing_z.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,z/comparing_z_processor=Z::ComparingZProcessor,comparings/populations/populations_comparing_mapper_processor=Comparings::Populations::PopulationsComparingMapperProcessor z/populations/populations_comparing_z_reporter=Z::Populations::PopulationsComparingZReporter > output/comparing_z_populations.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,z/comparing_z_processor=Z::ComparingZProcessor,comparings/regions/regions_comparing_mapper_processor=Comparings::Regions::RegionsComparingMapperProcessor z/regions/regions_comparing_z_reporter=Z::Regions::RegionsComparingZReporter > output/comparing_z_regions.html

bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,bb/comparing_bb_processor=Bb::ComparingBbProcessor,lib/processors/by_question_mapper_processor=ByQuestionMapperProcessor bb/common_comparing_bb_reporter=Bb::CommonComparingBbReporter > output/comparing_bb.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,bb/comparing_bb_processor=Bb::ComparingBbProcessor,comparings/populations/populations_comparing_mapper_processor=Comparings::Populations::PopulationsComparingMapperProcessor bb/populations/populations_comparing_bb_reporter=Bb::Populations::PopulationsComparingBbReporter > output/comparing_bb_populations.html
bundle exec ruby report.rb input/results comparings/comparing_storage=Comparings::ComparingStorage comparings/comparing_processor=Comparings::ComparingProcessor,bb/comparing_bb_processor=Bb::ComparingBbProcessor,comparings/regions/regions_comparing_mapper_processor=Comparings::Regions::RegionsComparingMapperProcessor bb/regions/regions_comparing_bb_reporter=Bb::Regions::RegionsComparingBbReporter > output/comparing_bb_regions.html
